name: Tests & Coverage Badges

on:
  push:
    branches:
      - main

jobs:
  update-badges:
    environment:
      name: CI
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      # this will take the entire vars context configured in the repository > environments
      # setting and convert it to JSON so we can automatically assign all the values to the
      # runner's environment
      VARS_CONTEXT: ${{ toJson(vars) }}
      TEST_YOUTUBE_UPLOADS_API_KEY: ${{ secrets.TEST_YOUTUBE_UPLOADS_API_KEY }}
      TEST_YOUTUBE_PLAYLISTS_API_KEY: ${{ secrets.TEST_YOUTUBE_PLAYLISTS_API_KEY }}
      TEST_DISCORD_WEBHOOK_ID: ${{ secrets.TEST_DISCORD_WEBHOOK_ID }}
      TEST_DISCORD_WEBHOOK_TOKEN: ${{ secrets.TEST_DISCORD_WEBHOOK_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Set env vars from vars context JSON
        run: |
          # Pipe the JSON string into jq
          echo "$VARS_CONTEXT" | 
          # Convert JSON object into an array of key-value pairs
          jq -r 'to_entries | 
          # Map over each key-value pair
          .[] | 
          # Format each pair as "KEY=VALUE" and append it all to the environment file
          "\(.key)=\(.value)"' >> $GITHUB_ENV
      - name: Install dependencies
        run: npm ci
      - name: Run all tests
        run: npm run ci:testall
      - name: Update badges
        run: npm run ci:badges
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "ci: update badges" || echo "No changes to commit"
          git push
